export const TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
export const CLEAR_TOO_MANY_REQUESTS = "CLEAR_TOO_MANY_REQUESTS";
export const CLEAR_REQUESTS = "CLEAR_REQUESTS";
export const ADD_NEW_REQUEST = "ADD_NEW_REQUEST";
