export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";

export const REQUEST_TEAMS_PENDING = "REQUEST_TEAMS_PENDING";
export const REQUEST_TEAMS_SUCCESS = "REQUEST_TEAMS_SUCCESS";
export const REQUEST_TEAMS_FAILED = "REQUEST_TEAMS_FAILED";

export const TOGGLE_TEAM_BOOKMARK_PENDING = "TOGGLE_TEAM_BOOKMARK_PENDING";
export const TOGGLE_TEAM_BOOKMARK_SUCCESS = "TOGGLE_TEAM_BOOKMARK_SUCCESS";
export const TOGGLE_TEAM_BOOKMARK_FAILED = "TOGGLE_TEAM_BOOKMARK_FAILED";

export const TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
export const CLEAR_TOO_MANY_REQUESTS = "CLEAR_TOO_MANY_REQUESTS";
export const CLEAR_REQUESTS_COUNTER = "CLEAR_REQUESTS_COUNTER";
